NAME: 'HK Crossover'
MODULE: 'HK_sma_crossover'
CLASS: 'HKSMAcrossOver'
INTERVAL: '1day'
PERIOD: 1
RISK_PC: 90
SIZING: 'risk'
PARAMETERS:
  sma: 9
  candle_lookback: 1 # look back over this many candles
  RR: 1
  exchange: 'NFO'
  product: 'futures'
  expiry: "2021-12-30T07:00:00.000Z"
  option_type: ""
  strike: ""
  start_time: "2021-10-01T07:00:00.000Z"
  end_time: "2021-12-23T07:00:00.000Z"

# Define pairs to monitor
WATCHLIST: ['NIFTY']