NAME: 'Luffy'
MODULE: 'Luffy'
CLASS: 'Strangles'
INTERVAL: '1minute'
PERIOD: 1
RISK_PC: 1
SIZING: 'risk'
PARAMETERS:
  candle_lookback: 10 # look back over this many candles
  RR: 4.0 # risk-to-reward ratio
  exit_buffer: 0.2 # price units
  name: 'BANKNIFTY'
  iciciCode: 'CNXBAN'
  exchange: 'NSE'
  product: 'OI'
  expiry: 'Weekly'
  contract: 'Current'
  option_type: "both"
  option_price: 100
  strike: "Dynamic"
  start_time: ""
  end_time: ""
# Define pairs to monitor
WATCHLIST: ['BANKNIFTY']
TRADE_INSTRUMENT: Dynamic
BACKTEST:
  start_time: ""
  end_time: ""