NAME: 'EMA Crossover'
MODULE: 'sma_momentum'
CLASS: 'SMAMomentum'
INTERVAL: '1minute'
PERIOD: 300
RISK_PC: 1
SIZING: 'risk'
PARAMETERS:
  sma_period: 44 # period of SMA
  candle_lookback: 4 # look back over this many candles
  RR: 4.0 # risk-to-reward ratio
  exit_buffer: 0.2 # price units
  exchange: 'NFO'
  product: 'futures'
  expiry: "2021-12-30T07:00:00.000Z"
  option_type: ""
  strike: ""
  start_time: "2021-10-01T07:00:00.000Z"
  end_time: "2021-12-23T07:00:00.000Z"
# Define pairs to monitor
WATCHLIST: ['NIFTY']